steps:
  # Step 1: Authenticate with GCP using Service Account stored in Secret Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Fetch the service account key from Secret Manager
        gcloud secrets versions access latest --secret="docgen-service-account-key" > /workspace/gcp-key.json
        gcloud auth activate-service-account --key-file=/workspace/gcp-key.json

  # Step 2: Set GCP project
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'config'
      - 'set'
      - 'project'
      - 'docgen-440809' # Replace with your GCP project ID

  # Step 3: Build and push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/docgen-440809/docgen-testenv:latest' # Replace with your service name
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/docgen-440809/docgen-testenv:latest'

  # Step 4: Deploy the Docker image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'your-service-name' # Replace with your Cloud Run service name
      - '--image'
      - 'gcr.io/docgen-440809/docgen-testenv:latest'
      - '--region'
      - 'your-region' # Replace with your region, e.g., us-central1
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # Optional: Remove if authentication is required
      -- '--set-env-vars'
      - |
        PORT=${_PORT},
        API_KEY=${_API_KEY},
        SF_ORG_ID=${_SF_ORG_ID},
        SF_USERNAME=${_SF_USERNAME},
        SF_CLIENT_ID=${_SF_CLIENT_ID},
        SERVICE_ACCOUNT=${_SERVICE_ACCOUNT},
        SF_ORG_ID_TWO=${_SF_ORG_ID_TWO},
        BASE_URL=${_BASE_URL},


substitutions:
  _PORT: 4350 # Replace with your environment variable values
  _API_KEY: "AIzaSyArxb3xZ5lTVpGrF6YbMsCrS9e8iPGLldY"
  _SF_ORG_ID: 00DWU00000BoiXu 
  _SF_ORG_ID_TWO: 00DZS00000BoiXu 
  _SF_USERNAME: cddev@org.com 
  _SF_CLIENT_ID: 3MVG9PwZx9R6_UrcKsn.dhKdoWYbj8AZY5Im_VSx5QB0C32PwXvuJiRaSOetY9cCvvHFEj7tZ2_RtwRcnaGV6 
  _BASE_URL: https://docgen-1027746116534.us-central1.run.app
  _SERVICE_ACCOUNT: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiZG9jZ2VuLTQ0MDgwOSIsCiAgInByaXZhdGVfa2V5X2lkIjogImFmYWU0MDdhNGRkNzE0NDM0ZDFmOTYyNWY2YzU3NjI3YjMzZTUwODQiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRElCTi93bEFaYzZMMDFcbjNPKzRVdVJIajZIeHI1SG82NnpxR09Ud1lGV2RCcitvN1ZWeWFNOHIzd1pmL285NDRkcEVUaTBSRlpuUEZHOFpcbm9zM3hWZ213K1ZmajdkL2o3a1NQb3IvOVMxRXpWOFExZVMzTUJNZ2hBYnp4ek1TQlVJWWxORHg2ZDdWTkFNbFJcbmJzbHpob2FiV3FubVFDRXkvcTRBcmZkNE9JcFBkbFpTMHRwMituOGFuMDVPeHlCWnlkMGd1ZUhFZ0NBeUMzSk1cbmtMYVNZOE55K0NwL3hiMHpjQ29Nb1BvYzA2aUhNUVA3bkdKSTk4WTFiRG9EMHFYRFpxZ2o4Mld1b3g1UTdWRkVcbjdmdnpqeXJzTGp4S1k1NEY5SjdSUnF1K3AyNXFpRGVaeWpTTklSZ2hWY0FSZVBJMFNWRldlT1dPcVFYQXRXaFhcbm42T0lCKzBqQWdNQkFBRUNnZ0VBT3BocS9qQnZHTUs1dzFEQkRVK0RQbytPVXA0cmNYK3hQVGNqd21PR1VTVUxcbitySGthVXJZL2pJc3pPeG5IWE9VbkpRR1VjM3hMQ0FCV0JKQW9LV2kyeXlBbWU0eXU3UXVjNkdxK3NvWXRLRE9cbmd4ZkgyYy9BelNLVU5vWFZQMGpXczRsMCtpK2RkangzdlpwbCs2ajZRQUswYVJaNlkxVUdwbjVRVS9ERVcvaDZcbnUreTNJZEVzOFpESmErcWdianFxQ2cvSURnbm5DWXNzTlRRbUd5anFzUDE2Rjk3bHJ5cW5tVHBacDRxZXkwVm5cbnF5YmlSS0JGNFdKSXEzQzY3OHJ3dHlPZ0xDV2NYc2pmbThhMFMxVXM3WUl2VnNGeWJGS2ovTERnY3pYTldrR2JcbnVZVE1CMTNzM1V6dFRnRXR4ellMKzl4ZVFvUWpOMHNibTgvSXFZczNpUUtCZ1FET3Zkdmg4MlBYUGVycEhzMXRcbld0MXVXZEV1c1UrTlMzdlNSL2xmL0hneE5uYlNWd1p2b3YrdTVkWnNRcGFyeXdFMXBTbHM4MVRuWVpWYndva3hcbjEwZWozQ2RvZU9SdmhVUzZDNU9MbXBTUlZRTWplSnU5aUxkRWlBYnBKd0Y5QVNsZnBkeTk3Zys4czJPM21XWG5cbklOa2RNOGtMakd1eTNjaG50RmFIMmJnb053S0JnUUQzclBrcmpMRUltcHlLZGNCd01ibVdKSWVTcVk3aVo4NFNcblZzQXRITmpQN3lPVUVIZFU4MDZDVTZreHBpMnp0TUhORTYyZldaTnNRTFdnTUZXRDNPVTArYXNRTC9LTGxxT2pcbmVDY0NNZFpYWFZaUWg2SVNreXhjYWtkOThwaWtPRnJwQ0RPaUQ3cEUvNll1V2hmUjJyc2pad3U0c0VVZFNvMjBcbm03aE92dkRVZFFLQmdRREl4ZTZzenE0dUVNNTZHRlRObDBtbGFncFFleGRUazNPck1nU0c1K3RkZDVRTEQwS0xcbjFkTFNhaGhEU0tPRU1JQjdOV3MyaUZUeTQzeW1BUlUxVnVrV3c2MXRzc0c5WDhIdm4yQnBXZlJmOHh3NkxWMnBcbndnU2d4QzFaN1d4dmxsbzByaUhpUFRnQlBJRmhndEpJbEVqbEtDNWRUY0FsazJhVTk3aDA4OFg1SHdLQmdISlJcbjZ1a0pGYVh0QjVoNVpZdmp4OC9mcUp3dm0zNHhmOUxETEEwbXBZVEUwdDFEQkhHM3BHTlBqbWNXVnozOWp2N0RcbnVINDI4RzhsSnpCN1h0MXdsbk52VW1BMFlYWEE0R05SMEYrWTlXQjUrcDlORzZnTE9veWxtYjR1dmZuKzhTZGlcbjI4SlFGQ0JKQ0VHWTRDbkRGbUh1N0dBaExLV3FoZUg1aG9jQ1oxTUpBb0dCQUxtbXIrZkVnc252Y2QwWnpRTnZcblM0dmVtQTF6WTBJUnVpYU1xcXFGRVNDbUtJbjhrRVRJbXErVHhjSDNaSWxzWUFONDBLVVFDVGdWZ3hJTXFNRjNcbnVSTWdSSWQvRHNhUEROa21iYXF5b0hRSVFUdEgvby9WdHlIQkxhMWhGKzc5TE9aVUdtdzJkRVdiaS94bnpZV2FcbjBYQWFkV0szMjBxK0c1eDllTlU5KzUza1xuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogIjEwMjc3NDYxMTY1MzQtY29tcHV0ZUBkZXZlbG9wZXIuZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMTA4OTgzNTUxNjUyMzA3MTAyMjMiLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5LzEwMjc3NDYxMTY1MzQtY29tcHV0ZSU0MGRldmVsb3Blci5nc2VydmljZWFjY291bnQuY29tIiwKICAidW5pdmVyc2VfZG9tYWluIjogImdvb2dsZWFwaXMuY29tIgp9Cg== 

  

timeout: '600s' # Optional: Timeout for the build process

