sonar.projectKey=CloudDesk_Gcp_Cloud_Docgen
sonar.organization=clouddesk
sonar.javascript.lcov.reportPaths='/coverage/lcov-report'
sonar.coverage.exclusions=**/*.test.js,**/*.spec.js,jest.config.js,jest.config.mjs,jest.setup.js
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.javascript.coverage.reportPaths='/coverage/lcov-report'