name: Build

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures the full history for better analysis

      # Step 2: Set environment variables (using GitHub Secrets)
      - name: Set environment variables
        run: |
          echo "PORT=${{ secrets.PORT }}" >> $GITHUB_ENV
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          echo "SF_ORG_ID=${{ secrets.SF_ORG_ID }}" >> $GITHUB_ENV
          echo "SF_USERNAME=${{ secrets.SF_USERNAME }}" >> $GITHUB_ENV
          echo "SF_CLIENT_ID=${{ secrets.SF_CLIENT_ID }}" >> $GITHUB_ENV
          echo "SERVICE_ACCOUNT=${{ secrets.SERVICE_ACCOUNT }}" >> $GITHUB_ENV

      # Step 3: Create GCP credentials file
      - name: Create GCP credentials file
        run: |
          echo "${{ secrets.GCP_CREDENTIALS_JSON }}" > "$GITHUB_WORKSPACE/docgen-440809-afae407a4dd7.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/docgen-440809-afae407a4dd7.json" >> $GITHUB_ENV

  - name: Install LibreOffice
      run: |
        sudo apt-get update
        sudo apt-get install -y libreoffice
        sudo apt-get install -y libreoffice-writer
        # Verify installation
        soffice --version

    - name: Create output directory
      run: |
        mkdir -p templates
        chmod 777 templates


      # Step 4: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 5: Run Jest Tests with Coverage
      - name: Run Jest Tests
        run: npm test -- --coverage

      # Step 6: Run SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
