name: Build and Test

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Decode and Save GCP Credentials
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" | base64 --decode > $GITHUB_WORKSPACE/gcp-credentials.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/gcp-credentials.json" >> $GITHUB_ENV

      - name: Print Decoded GCP Credentials (Debugging)
        run: |
          cat $GITHUB_WORKSPACE/gcp-credentials.json

      - name: Verify GCP Credentials JSON Structure
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          jq empty $GITHUB_WORKSPACE/gcp-credentials.json || (echo "GCP credentials JSON is invalid." && exit 1)

      - name: Install Dependencies
        run: npm install

      - name: Run Jest Tests with Coverage
        run: npm test -- --coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Validate GCP Credentials (with gcloud)
        run: |
          gcloud auth activate-service-account --key-file=$GITHUB_WORKSPACE/gcp-credentials.json
          gcloud auth list
