# .github/workflows/deploy.yml
name: Deploy Pipeline

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production
        run: |
          # Run your deployment script or command here
          echo "Deploying application..."
