# .github/workflows/dev.yml
name: Dev Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Create pull request to test branch
        if: success()
        run: |
          gh pr create --title "Promote from dev to test" --body "Auto PR from dev to test" --base test --head dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
